2018-07-02 20:46:32 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=430 from 2018-07-02 18:39:01.547778)
2018-07-02 20:46:59 ERROR (MainThread) [homeassistant.components.camera] Error while setting up platform netatmo
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/camera/netatmo.py", line 40, in setup_platform
    for camera_name in data.get_camera_names():
  File "/usr/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 82, in get_camera_names
    self.update()
  File "/usr/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 319, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 113, in update
    self.camera_data = pyatmo.CameraData(self.auth, size=100)
  File "/usr/lib/python3.6/site-packages/smart_home/Camera.py", line 50, in __init__
    for e in self.rawData['homes'][i]['events']:
KeyError: 'events'
2018-07-02 20:47:05 WARNING (MainThread) [homeassistant.setup] Setup of config is taking over 10 seconds.
2018-07-02 20:47:12 WARNING (MainThread) [homeassistant.setup] Setup of xiaomi_aqara is taking over 10 seconds.
2018-07-02 20:47:24 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform netatmo
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/binary_sensor/netatmo.py", line 73, in setup_platform
    if not data.get_camera_names():
  File "/usr/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 82, in get_camera_names
    self.update()
  File "/usr/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 319, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 113, in update
    self.camera_data = pyatmo.CameraData(self.auth, size=100)
  File "/usr/lib/python3.6/site-packages/smart_home/Camera.py", line 50, in __init__
    for e in self.rawData['homes'][i]['events']:
KeyError: 'events'
2018-07-02 20:47:48 ERROR (SyncWorker_3) [homeassistant.components.sensor.cert_expiry] Cannot connect to mastropino.homepc.it
2018-07-02 20:47:51 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-07-02 20:48:03 WARNING (SyncWorker_2) [netdisco.ssdp] Error fetching description at http://192.168.0.50:45555/wps_device.xml
